version: '3.8'

services:
  flore-backend:
    build:
      context: ./backend/Floreria.API
      dockerfile: Dockerfile
    container_name: floreria-backend
    restart: unless-stopped
    environment:
      ConnectionStrings__DefaultConnection: "Server=floreria-mysql;Port=3306;Database=floreria_lacarreta_db;User=root;Password=FloreriaRootPass2026!;AllowPublicKeyRetrieval=True;SslMode=None;TreatTinyAsBoolean=true;AllowUserVariables=true;CharSet=utf8mb4;"
      ASPNETCORE_ENVIRONMENT: "Production"
      ASPNETCORE_URLS: "http://+:5000"
    expose:
      - "5000"
    networks:
      - default
      - coolify

  flore-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: floreria-frontend
    restart: unless-stopped
    depends_on:
      - flore-backend
    expose:
      - "80"
    labels:
      - coolify.managed=true
      - "coolify.fqdn=https://gestionfloreria.molinazdev.lat"
      - "traefik.http.services.flore-frontend.loadbalancer.server.port=80"
    networks:
      - default
      - coolify

networks:
  default:
  coolify:
    external: true
